### ISSUE TITLE
hey can i disable fullscreen mode ?

### ISSUE THREAD

**Issue by boomnos** [Ashesh3/RosMultiHackv99#1]
when fullscreen i can't see esp or anything in this hack but when i press window button hack is show and get into ros game hack is hide.

**Comment by Ashesh3** [comment]
````
            SetWindowLong(aaaa, GWL_STYLE, (WS_VISIBLE));
            Rectangle resolution = Screen.PrimaryScreen.Bounds;
            MoveWindow(aaaa, resolution.Top, resolution.Left, resolution.Width, resolution.Height, true);
            ShowWindowAsync(aaaa, 3);
````

Remove these lines, it won't go fullscreen then.

https://github.com/Ashesh3/RosMultiHackv99/blob/master/Main.cs#L128-L131


+SmartAim won't work

**Comment by boomnos** [comment]
thank you master
