### ISSUE TITLE
Update new Offsets

### ISSUE THREAD

**Issue by hodangkhoa** [Ashesh3/RosMultiHackv99#10]
Hi Bro,
Can u send me new Offsets Source
Thank a lot!

**Comment by LexBacker** [comment]
Updating the game 07.02.18 - update the Offsets in the code please)

**Comment by ghost** [comment]
**Re-download the project**

Offset has been updated to the last version. 
[Maths.cs](https://github.com/Ashesh3/RosMultiHackv99/commit/016ce5450decfb2dd7bd4fea6fc7bbe1f1f1a78d) and [Offsets.cs](https://github.com/Ashesh3/RosMultiHackv99/commit/923d3eadd726cad0993719b66883f9bf6011151c)

thanks to @Ashesh3

**Comment by Ashesh3** [comment]
Thanks for the clarification @Bogar29
