### ISSUE TITLE
SharpDX.D3DCompiler

### ISSUE THREAD

**Issue by ghost** [Ashesh3/RosMultiHackv99#2]
I get an error when opening this project, all the packages I have installed via Nuget but still error. like this : 

> NuGet Package restore failed for project Ros External Beta: 'SharpDX.D3DCompiler' already has a dependency defined for 'SharpDX'

![image](https://user-images.githubusercontent.com/8254072/35828029-af635648-0af0-11e8-92bc-018895c9be68.png)

and when I try to restore the Nuget package, I get a message like this

![image](https://user-images.githubusercontent.com/8254072/35827998-996ca308-0af0-11e8-86bf-2751428f1644.png)

**Comment by Ashesh3** [comment]
Who told you to install sharpDX?

That's not even used in this project , just remove all SharpDX packages. Re-download this project. Don't add SharpDX ,it's not necessary

**Comment by ghost** [comment]
thanks dude

I think it's important.
I just made changes to the "packages.config" file, deleting all packages of SharpDX and working well.

keep sharing XD

**Comment by Ashesh3** [comment]
@Bogar29 Thanks, I changed the file, please confirm if it looks like yours now

https://github.com/Ashesh3/RosMultiHackv99/commit/794e1a4bf07007405313416a130d949df53a2090

**Comment by ghost** [comment]
@Ashesh3 yes it looks beautiful now 👍 😄
