### ISSUE TITLE
How disable items esp, remove from script

### ISSUE THREAD

**Issue by jockzz** [Ashesh3/RosMultiHackv99#3]
How to delete items esp from script? I want it show only player esp.

**Comment by Ashesh3** [comment]
Change all these IF conditions to 
`if(false)`

https://github.com/Ashesh3/RosMultiHackv99/blob/master/Main.cs#L310
https://github.com/Ashesh3/RosMultiHackv99/blob/master/Main.cs#L317
https://github.com/Ashesh3/RosMultiHackv99/blob/master/Main.cs#L325
https://github.com/Ashesh3/RosMultiHackv99/blob/master/Main.cs#L337
https://github.com/Ashesh3/RosMultiHackv99/blob/master/Main.cs#L344

**Comment by jockzz** [comment]
Thanks
