### ISSUE TITLE
Mouse Speed

### ISSUE THREAD

**Issue by Invalidity** [Ashesh3/RosMultiHackv99#4]
It's weird, whenever you run the program the pointer speed in mouse properties goes up to max. I haven't really checked the codes thoroughly because I've been busy and I'm on my phone.

**Comment by Ashesh3** [comment]
This shouldn't happen, please provide more details.

**Comment by zombozo12** [comment]
i got same issue

**Comment by Invalidity** [comment]
I think it's probably because I included SharpDX packages in there when you said in another closed issue that it wasn't needed. Will have to check later. But I noticed in main.cs that you called SPI_GETMOUSESPEED, what are you using it for?

**Comment by Ashesh3** [comment]
SPI_GETMOUSESPEED is your ingame sensitivity

**Comment by Invalidity** [comment]
I'm not sure, but I think its the line where you declared res in main.cs:
`int res = WinAPI.SystemParametersInfo(113, 0, 20, 0);`
Since 20 is the highest windows mouse sensitivity and 10 is the default:
`int res = WinAPI.SystemParametersInfo(113, 0, 10, 0);`

But hey, I'm not sure, C# isn't my thing lol

**Comment by Ashesh3** [comment]
@Invalidity SystemParametersInfo is nowhere used in this code

**Comment by Ashesh3** [comment]
Fixed:

https://github.com/Ashesh3/RosMultiHackv99/commit/761e02c0e47f360ef60c155800b6af051bbbbdaf
