### ISSUE TITLE
how to use this source ?

### ISSUE THREAD

**Issue by sdquang75** [Ashesh3/RosMultiHackv99#5]
i'm newbie, pls help me, there are too many errors

**Comment by sdquang75** [comment]
https://imgur.com/a/FVBMy

**Comment by Ashesh3** [comment]
SharpDx is not needed, just remove it.

**Comment by sdquang75** [comment]
how to remove ? pls

**Comment by Ashesh3** [comment]
Pm on Discord:

NewSweetLife#0316
