### ISSUE TITLE
Frozen ESP

### ISSUE THREAD

**Issue by okatokat** [Ashesh3/RosMultiHackv99#7]
sometimes ESP freezes.

**Comment by Invalidity** [comment]
Is it just the ESP? Lately I've been testing it out on different PCs and on some the whole program freezes on prolonged uses. I just fix it manually by restarting the cheat.

**Comment by Ashesh3** [comment]
The hack freezes after sometime, randomly. Known issue.

**Comment by okatokat** [comment]
yes for me its only ESP. cause its only the feature i use

**Comment by Ashesh3** [comment]
Reopen if this happens for new update.

**Comment by Xin1337** [comment]
Still happens to me.

**Comment by chrlsrara** [comment]
same here happens to me.
